import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Player from "../components/MultiPlayer";
import Grid from "../components/grid";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>ALIENS REAL FOOTAGE!!!1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        style={{
          backgroundImage: `url(https://i.ibb.co/tbpgFyZ/istockphoto-1211526766-170667a.jpg`,
        }}
        className="h-screen w-screen"
      >
        <Grid />
      </main>
    </div>
  );
}
